_G.assets = {
    fonts = {
        dialog = "assets/fonts/diamond_12",
        menu = {
            tiny = "assets/fonts/m42/m42-7",
            small = "assets/fonts/m42/m42-8",
            medium = "assets/fonts/m42/m42-10",
            large = "assets/fonts/m42/m42-12",
            huge = "assets/fonts/m42/m42-14",
            giant = "assets/fonts/m42/m42-16",
        },
    },
    images = {
        logo = "assets/images/logo",
        tileset = "assets/images/tileset",
        hudPanel = "assets/images/hud-panel",
        speech = "assets/images/speech",
        speechBButton = "assets/images/speech-b-button",
        box = "assets/images/box",
        background = "assets/images/background",
        background2 = "assets/images/background-2",
        menu = {
            buttonAStart = "assets/images/menu/A-Start",
            buttonAContinue = "assets/images/menu/A-Continue",
            buttonBLevelSelect = "assets/images/menu/B-LevelSelect",
            title = "assets/images/menu/title"
        },
        botFaces = {
            [1] = "assets/images/bots/B-face",
            [2] = "assets/images/bots/C-face",
            [3] = "assets/images/bots/D-face",
            [4] = "assets/images/bots/E-face",
            [5] = "assets/images/bots/F-face",
            [6] = "assets/images/bots/G-face",
            [7] = "assets/images/bots/H-face",
        }
    },
    imageTables = {
        logicBlock = "assets/images/logic-block",
        collectibles = "assets/images/collectibles",
        questionMark = "assets/images/questionmark",
        buttons = "assets/images/buttons",
        menuArrows = "assets/images/menu-arrows",
        drillableBlock = "assets/images/drillableblock",
        player = "assets/images/player",
        playerDarkness = "assets/images/player-darkness",
        elevator = "assets/images/elevator",
        elevatorTrack = "assets/images/elevator-track",
        warp = "assets/images/warp",
        guiRescueBots = "assets/images/gui-rescued-bots",
        particlesDrilling = "assets/images/particles-drilling",
        transition = {
            right = "assets/images/transition-right",
            bottom = "assets/images/transition-bottom",
        },
        bots = {
            BKPK = "assets/images/bots/BKPK",
            ELDR = "assets/images/bots/ELDR",
            GRN = "assets/images/bots/GRN",
            JPL = "assets/images/bots/JPL",
            MOP = "assets/images/bots/MOP",
            SNTRY = "assets/images/bots/SNTRY",
            WOP = "assets/images/bots/WOP",
            BTL = "assets/images/bots/BTL",
            ELF = "assets/images/bots/ELF",
            HGHT = "assets/images/bots/HGHT",
            LFS = "assets/images/bots/LFS",
            PNG = "assets/images/bots/PNG",
            SPL = "assets/images/bots/SPL",
            YNGR = "assets/images/bots/YNGR",
            BZ = "assets/images/bots/BZ",
            EYES = "assets/images/bots/EYES",
            HGL = "assets/images/bots/HGL",
            LPL = "assets/images/bots/LPL",
            PONY = "assets/images/bots/PONY",
            SPR = "assets/images/bots/SPR",
            ZUG = "assets/images/bots/ZUG",
            CMT = "assets/images/bots/CMT",
            FFLY = "assets/images/bots/FFLY",
            INF = "assets/images/bots/INF",
            MIPA = "assets/images/bots/MIPA",
            RKD = "assets/images/bots/RKD",
            VRP = "assets/images/bots/VRP",
            DGR = "assets/images/bots/DGR",
            GPL = "assets/images/bots/GPL",
            JPK = "assets/images/bots/JPK",
            MNTS = "assets/images/bots/MNTS",
            RUD = "assets/images/bots/RUD",
            WGHT = "assets/images/bots/WGHT"
        }
    },
    sounds = {
        collect = "assets/sfx/collect",
        cheatUnlock = "assets/sfx/cheat-unlock",
        jump = "assets/sfx/jump",
        powerUp = "assets/sfx/power-up",
        powerDown = "assets/sfx/power-down",
        collectiblePickup = "assets/sfx/collectible-pickup",
        speech = "assets/sfx/speech",
        errorAction = "assets/sfx/error-action",
        errorSavePoint = "assets/sfx/error-save-point",
        menuSelect = "assets/sfx/menu-select",
        robotSave = {
            [1] = "assets/sfx/robot-save",
            [2] = "assets/sfx/robot-save-2",
            [3] = "assets/sfx/robot-save-3"
        },
        warpAmbient = "assets/sfx/warp-ambient",
        warpAction = "assets/sfx/warp-action",
        savepointActivate = "assets/sfx/savepoint-activate",
        blockCrush = {
            [1] = "assets/sfx/block-crush-1",
            [2] = "assets/sfx/block-crush-2",
            [3] = "assets/sfx/block-crush-3",
            [4] = "assets/sfx/block-crush-4",
        },
        drill = "assets/sfx/drill",
        swoosh = "assets/sfx/swoosh"
    },
    music = {
        game = "assets/music/playtester-theme",
        menu = "assets/music/menu-theme"
    }
}
